- name: Install Grafana GPG key
  ansible.builtin.rpm_key:
    key: https://rpm.grafana.com/gpg.key
    state: present

- name: Install Grafana
  ansible.builtin.yum:
    name: "https://dl.grafana.com/oss/release/grafana-{{ grafana_version }}.{{ grafana_arch }}.rpm"
    state: present

- name: Enable and start Grafana service
  ansible.builtin.systemd:
    name: grafana-server
    enabled: yes
    state: started