- name: Docker Installation
  hosts: host0
  become: true
  gather_facts: true

  pre_tasks:

    - name: Check instance machine
      ansible.builtin.fail:
        msg: "this ansible code only for redhat base distro"
      when: ansible_os_family != "RedHat"

    - name: Update package
      ansible.builtin.dnf:
        name: "*"
        state: latest

  tasks:

    - name: Install Docker
      ansible.builtin.dnf:
        name: docker
        state: latest

    - name: Starting docker service
      ansible.builtin.systemd_service:
        name: docker
        state: started
        enabled: true

    - name: Adding user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      register: add_to_docker_group_result

    - name: Reset ssh connection
      when: add_to_docker_group_result.changed == true
      ansible.builtin.meta: reset_connection

    - name: Check docker
      ansible.builtin.shell: docker --version
      register: docker_check

    - name: Print the output
      ansible.builtin.debug:
        msg: "{{ docker_check.stdout }}"