- name: Kubectl Installation
  hosts: host0
  become: true
  gather_facts: true

  pre_tasks:

    - name: Check instance machine
      ansible.builtin.fail:
        msg: "this ansible code only for redhat base distro"
      when: ansible_os_family != "RedHat"

    - name: Update package
      ansible.builtin.dnf:
        name: "*"
        state: latest

  tasks:

    - name: Donwload kubectl binary
      ansible.builtin.include_tasks: download-kubectl.yaml

    - name: Verivy kubectl binary with the checksum
      ansible.builtin.shell: echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
      register: kubectl_bin_check

    - name: Print the verify result
      ansible.builtin.debug:
        msg: "{{ kubectl_bin_check.stdout }}"

    - name: Instal kubectl binary
      when: "kubectl_bin_check.stdout == 'kubectl: OK'"
      ansible.builtin.command: sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

    - name: Check kubectl installed version
      ansible.builtin.command: kubectl version --client
      register: kubectl_check_version

    - name: Print the kubetcl version
      ansible.builtin.debug:
        msg: "{{ kubectl_check_version.stdout }}"
