---
- name: Update docker image
  hosts: web_server
  become: true
  gather_facts: false

  vars:
    image_name: "adhamfaraitodi/temansoal"
    container_name: "temansoal"
    old_tag: "1.0.0"
    new_tag: "1.0.0"

  tasks:
    - name: Pull the new Docker image
      ansible.builtin.command:
        cmd: "docker pull {{ image_name }}:{{ new_tag }}"
      register: pull_result

    - name: Stop the existing container
      ansible.builtin.command:
        cmd: "docker stop {{ container_name }}"
      ignore_errors: yes

    - name: Remove the existing container
      ansible.builtin.command:
        cmd: "docker rm {{ container_name }}"
      ignore_errors: yes

    - name: Run the container with the new image
      ansible.builtin.command:
        cmd: docker container run -itd --name {{ container_name }} -p 80:3000 {{ image_name }}:{{ new_tag }}
